version: '3.7'
services:

  dashboard:
    build: 
      context: ./
    container_name: ${COMPOSE_PROJECT_NAME}_dashboard
    hostname: ${COMPOSE_PROJECT_NAME}_dashboard
    restart: always
    ports:
      - 5000:80
    volumes:
      - output:/wd/output
    networks:
      - network
    environment:
      - PYTHONUNBUFFERED=1  # send python output to container log


networks:
  network:
    driver: bridge


volumes:
  output:
